/**
 * Markdown section parser for ghexplainer analysis output.
 *
 * The AI generates analyses structured as 11 top-level sections using
 * the format: `# N. Section Title` (e.g., `# 1. Repository Overview`).
 * This module extracts those sections into structured data so callers can:
 * - Display individual sections in the UI or CLI
 * - Export the analysis as structured JSON
 * - Build section-aware table of contents
 */

export interface AnalysisSection {
  /** Section number (1–11) */
  id: number;
  /** Section title (e.g. "Repository Overview") */
  title: string;
  /** Section body — everything between this section header and the next */
  content: string;
}

/**
 * Regex that matches top-level section headers generated by the AI.
 * Matches lines of the form: `# 1. Repository Overview`
 * Captured groups: (1) section number, (2) section title
 */
const SECTION_HEADER_RE = /^#\s+(\d+)\.\s+(.+)$/m;

/**
 * Parse all sections from an analysis markdown document.
 * Returns them in document order.
 *
 * Sections that are present but have no body text yield an empty `content`.
 * Lines that precede the first section header are discarded (preamble).
 *
 * @example
 *   const sections = extractSections(markdown);
 *   // → [{ id: 1, title: "Repository Overview", content: "..." }, ...]
 */
export function extractSections(markdown: string): AnalysisSection[] {
  if (!markdown || !markdown.trim()) return [];

  const lines = markdown.split("\n");
  const sections: AnalysisSection[] = [];
  let currentId: number | null = null;
  let currentTitle = "";
  const bodyLines: string[] = [];

  function flush() {
    if (currentId === null) return;
    sections.push({
      id: currentId,
      title: currentTitle,
      content: bodyLines.join("\n").trim(),
    });
  }

  for (const line of lines) {
    const match = line.match(SECTION_HEADER_RE);
    if (match) {
      flush();
      bodyLines.length = 0;
      currentId = parseInt(match[1], 10);
      currentTitle = match[2].trim();
    } else if (currentId !== null) {
      bodyLines.push(line);
    }
    // Lines before the first section header are ignored (preamble)
  }

  flush();
  return sections;
}

/**
 * Extract a single section by its numeric ID (1–11).
 * Returns `null` when the section is not found in the document.
 *
 * @example
 *   const overview = getSection(markdown, 1);
 *   // → { id: 1, title: "Repository Overview", content: "..." }
 */
export function getSection(markdown: string, id: number): AnalysisSection | null {
  return extractSections(markdown).find((s) => s.id === id) ?? null;
}

/**
 * Extract a section by its title (case-insensitive, leading/trailing
 * whitespace ignored).
 * Returns `null` when no section with a matching title is found.
 *
 * @example
 *   const arch = getSectionByTitle(markdown, "Architecture & Design");
 */
export function getSectionByTitle(
  markdown: string,
  title: string
): AnalysisSection | null {
  const normalised = title.trim().toLowerCase();
  return (
    extractSections(markdown).find(
      (s) => s.title.toLowerCase() === normalised
    ) ?? null
  );
}
